<a href="https://colab.research.google.com/github/duongdqq/TF_guide/blob/master/1_sequential_api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf 
from tensorflow import keras
from tensorflow.keras import layers

## When to use a Sequential model

1st solution

In [ ]:
model = tf.keras.models.Sequential(
    [
     tf.keras.layers.Dense(2, activation='relu', name='layer1'),
     tf.keras.layers.Dense(3, activation='relu', name='layer2'),
     tf.keras.layers.Dense(4, name='layer3')
    ]
)

x = tf.ones((3, 3))
y = model(x)

In [ ]:
model.get_weights()

[array([[ 0.97940135,  0.3063892 ],
        [-0.6929993 , -0.57991654],
        [-0.41544998,  0.51891065]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.89272285, -0.68153346,  0.4195664 ],
        [ 0.56005704,  0.8807472 ,  0.29390073]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[ 0.6894374 , -0.52499425, -0.02250105,  0.6012949 ],
        [ 0.5205251 ,  0.43238807, -0.6958186 , -0.052441  ],
        [ 0.5812378 , -0.7355262 ,  0.5472218 , -0.49196643]],
       dtype=float32),
 array([0., 0., 0., 0.], dtype=float32)]

In [ ]:
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.2491626 , -0.03174618, -0.11400835,  0.03582177],
       [ 0.2491626 , -0.03174618, -0.11400835,  0.03582177],
       [ 0.2491626 , -0.03174618, -0.11400835,  0.03582177]],
      dtype=float32)>

2nd solution

In [ ]:
layer1 = tf.keras.layers.Dense(2, activation='relu', name='layer1')
layer2 = tf.keras.layers.Dense(3, activation='relu', name='layer2')
layer3 = tf.keras.layers.Dense(4, name='layer3')

In [ ]:
x = tf.ones((3, 3))
y = layer3(layer2(layer1(x)))

In [ ]:
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-1.1452495 , -0.20503402,  0.2149037 , -0.2870614 ],
       [-1.1452495 , -0.20503402,  0.2149037 , -0.2870614 ],
       [-1.1452495 , -0.20503402,  0.2149037 , -0.2870614 ]],
      dtype=float32)>

# Creating a Sequential model

1st solution

In [ ]:
model = tf.keras.models.Sequential(
    [
     tf.keras.layers.Dense(2, activation='relu'),
     tf.keras.layers.Dense(3, activation='relu'),
     tf.keras.layers.Dense(4)
    ]
)

In [ ]:
model.layers

2nd solution

In [ ]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(2, 'relu'))
model.add(tf.keras.layers.Dense(3, 'relu'))
model.add(tf.keras.layers.Dense(4))
model.layers

use pop() to remove the last layer

In [ ]:
model.pop()
model.layers

In [ ]:
len(model.layers)

2

In [ ]:
x = tf.ones((7, 3))
y = model(x)

In [ ]:
model.get_weights()

[array([[-0.23019892,  0.89788675],
        [ 0.13643837, -0.63621503],
        [-0.31737816,  0.20696044]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.3184811 , -0.55060464,  0.5976082 ],
        [-0.35282922,  0.57750165,  0.46742558]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]

In [ ]:
model.weights

[<tf.Variable 'sequential_21/dense_30/kernel:0' shape=(3, 2) dtype=float32, numpy=
 array([[-0.23019892,  0.89788675],
        [ 0.13643837, -0.63621503],
        [-0.31737816,  0.20696044]], dtype=float32)>,
 <tf.Variable 'sequential_21/dense_30/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'sequential_21/dense_31/kernel:0' shape=(2, 3) dtype=float32, numpy=
 array([[ 0.3184811 , -0.55060464,  0.5976082 ],
        [-0.35282922,  0.57750165,  0.46742558]], dtype=float32)>,
 <tf.Variable 'sequential_21/dense_31/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

name argument to name a layer. This is for TensorBoard

In [ ]:
model = keras.Sequential(name="my_sequential")
model.add(layers.Dense(2, activation="relu", name="layer1"))
model.add(layers.Dense(3, activation="relu", name="layer2"))
model.add(layers.Dense(4, name="layer3"))

## Specifying the input shape in advance

* any layer needs to know the input shape to create weight
* when we do not initialize the input shape, the layer has no weights

In [ ]:
# from here I do not use tf.keras.layers.*** anymore
layer = layers.Dense(3, input_shape=(1,))
layer.weights

[]

* size of weight is equivalent to the number of column of input shape

In [ ]:
x = tf.ones((1, 4))
y = layer(x)
layer.weights

[<tf.Variable 'dense_29/kernel:0' shape=(4, 3) dtype=float32, numpy=
 array([[-0.7598375 ,  0.42093265, -0.43834162],
        [-0.39984542,  0.33802915, -0.27634346],
        [ 0.26255095, -0.6277422 , -0.697833  ],
        [-0.1535163 ,  0.11154997,  0.29973853]], dtype=float32)>,
 <tf.Variable 'dense_29/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

* apply to Sequential model
* if we do not initialize the input, model isnt built. When calling model.weights

In [ ]:
# model = tf.keras.models.Sequential()
model = keras.Sequential(
    [
     layers.Dense(2, 'relu'),
     layers.Dense(3, 'relu'),
     layers.Dense(4)
    ]
)
x = tf.ones((3, 9))
y = model(x)

In [ ]:
model.weights

[<tf.Variable 'sequential_23/dense_36/kernel:0' shape=(9, 2) dtype=float32, numpy=
 array([[-0.27617458,  0.40747005],
        [-0.40547305,  0.444977  ],
        [ 0.37908977, -0.24590364],
        [-0.49413425, -0.17516285],
        [-0.51124763, -0.16528213],
        [ 0.38304955,  0.06321055],
        [ 0.65624636, -0.14557976],
        [ 0.06252664, -0.73115975],
        [-0.29463923, -0.1790272 ]], dtype=float32)>,
 <tf.Variable 'sequential_23/dense_36/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'sequential_23/dense_37/kernel:0' shape=(2, 3) dtype=float32, numpy=
 array([[-0.2059794 , -1.036982  ,  0.22377431],
        [-1.0271919 ,  0.9168682 , -0.6118772 ]], dtype=float32)>,
 <tf.Variable 'sequential_23/dense_37/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>,
 <tf.Variable 'sequential_23/dense_38/kernel:0' shape=(3, 4) dtype=float32, numpy=
 array([[-0.49810433,  0.07568264,  0.6114681 , -0.02850169],
     

In [ ]:
len(model.weights)

6

* after model is built successfully. We can call summary()

In [ ]:
model.summary()

Model: "sequential_23"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_36 (Dense)             multiple                  20        
_________________________________________________________________
dense_37 (Dense)             multiple                  9         
_________________________________________________________________
dense_38 (Dense)             multiple                  16        
Total params: 45
Trainable params: 45
Non-trainable params: 0
_________________________________________________________________


* should build model incrementally

In [ ]:
model = keras.Sequential()
model.add(keras.Input(shape=(4,)))
model.add(layers.Dense(2, 'relu'))
model.summary()

Model: "sequential_25"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_40 (Dense)             (None, 2)                 10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


* keras.Input isnt a layer

In [ ]:
model.layers

* alternative solution to create an input shape

In [ ]:
model = keras.Sequential()
model.add(layers.Dense(2, 'relu', input_shape=(4,)))
model.summary()

Model: "sequential_26"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_41 (Dense)             (None, 2)                 10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.weights

[<tf.Variable 'dense_41/kernel:0' shape=(4, 2) dtype=float32, numpy=
 array([[-0.04748654, -0.25944352],
        [ 0.11995029, -0.8951616 ],
        [-0.95233417, -0.8552592 ],
        [-0.16530395,  0.24956846]], dtype=float32)>,
 <tf.Variable 'dense_41/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]

## A common debugging workflow: add() + summary()

In [ ]:
model = keras.Sequential()
model.add(keras.Input(shape=(250, 250, 3)))
model.add(layers.Conv2D(32, 5, strides=2, activation='relu'))
model.add(layers.Conv2D(32, 3, activation='relu'))
model.add(layers.MaxPooling2D(strides=3))

model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_27 (Conv2D)           (None, 123, 123, 32)      2432      
_________________________________________________________________
conv2d_28 (Conv2D)           (None, 121, 121, 32)      9248      
_________________________________________________________________
max_pooling2d_9 (MaxPooling2 (None, 40, 40, 32)        0         
Total params: 11,680
Trainable params: 11,680
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.add(layers.Conv2D(32, 3, activation='relu'))
model.add(layers.Conv2D(32, 3, activation='relu'))
model.add(layers.MaxPooling2D(3))
model.add(layers.Conv2D(32, 3, activation='relu'))
model.add(layers.Conv2D(32, 3, activation='relu'))
model.add(layers.MaxPooling2D(2))

model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_27 (Conv2D)           (None, 123, 123, 32)      2432      
_________________________________________________________________
conv2d_28 (Conv2D)           (None, 121, 121, 32)      9248      
_________________________________________________________________
max_pooling2d_9 (MaxPooling2 (None, 40, 40, 32)        0         
_________________________________________________________________
conv2d_29 (Conv2D)           (None, 38, 38, 32)        9248      
_________________________________________________________________
conv2d_30 (Conv2D)           (None, 36, 36, 32)        9248      
_________________________________________________________________
max_pooling2d_10 (MaxPooling (None, 12, 12, 32)        0         
_________________________________________________________________
conv2d_31 (Conv2D)           (None, 10, 10, 32)      

In [ ]:
model.add(layers.GlobalMaxPooling2D())
# add a classification layer
model.add(layers.Dense(10))

model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_27 (Conv2D)           (None, 123, 123, 32)      2432      
_________________________________________________________________
conv2d_28 (Conv2D)           (None, 121, 121, 32)      9248      
_________________________________________________________________
max_pooling2d_9 (MaxPooling2 (None, 40, 40, 32)        0         
_________________________________________________________________
conv2d_29 (Conv2D)           (None, 38, 38, 32)        9248      
_________________________________________________________________
conv2d_30 (Conv2D)           (None, 36, 36, 32)        9248      
_________________________________________________________________
max_pooling2d_10 (MaxPooling (None, 12, 12, 32)        0         
_________________________________________________________________
conv2d_31 (Conv2D)           (None, 10, 10, 32)      

## Feature extraction with a Sequential model

* Quickly creating a model that extracts the outputs of all intermediate layers in a Sequential model

In [ ]:
initial_model = keras.Sequential(
    [
     keras.Input(shape=(250, 250, 3)),
     layers.Conv2D(32, 5, strides=2, activation='relu'),
     layers.Conv2D(32, 3, activation='relu'),
     layers.Conv2D(32, 3, activation='relu'),
    ]
)
feature_extractor = keras.Model(
    inputs=initial_model.inputs,
    outputs=[layer.output for layer in initial_model.layers]
)
# Call feature extractor on test input.
x = tf.ones((1, 250, 250, 3))
features = feature_extractor(x)

* similar example only extracts features from one layer

In [ ]:
initial_model = keras.Sequential(
    [
     keras.Input(shape=(250, 250, 3)),
     layers.Conv2D(32, 5, strides=2, activation='relu'),
     layers.Conv2D(32, 3, activation='relu', name='my_intermediate_layer'),
     layers.Conv2D(32, 3, activation='relu')
    ]
)
feature_extractor = keras.Model(
    inputs=initial_model.inputs,
    outputs=initial_model.get_layer(name='my_intermediate_layer').output
)
# Call feature extractor on test input.
x = tf.ones((1, 250, 250, 3))
features = feature_extractor(x)

## Transfer learning with a Sequential model

* For freezing all layers except the last one. 
* Let's iterate over model.layers and set layer.trainable=False on each layer except the last one

In [ ]:
model = keras.Sequential([
    keras.Input(shape=(784)),
    layers.Dense(32, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(10),
])

model.load_weights(...)  # direction of pre trained weight

# freeze all layers except the last one
for layer in model.layers[:-1]:
  layer.trainable = False

# recomplie and train 
# only update the weights of the last layer
model.compile(...)
model.fit(...)

AttributeError: ignored

* 2nd method
* stack a pre trained model and some freshly initialized classification layers

In [ ]:
base_model = keras.applications.Xception(
    weights='imagenet',
    include_top=False,
    pooling='avg'
)

# freeze the base model
base_model.trainable = False

# add a trainable classifier on top
model = keras.Sequential(
    [
     base_model,
     layers.Dense(1000)
    ]
)

# compile and train
model.compile(...)
model.fit(...)

83689472/83683744 [==============================] - 0s 0us/step


ValueError: ignored